Re-declare maven-javadoc-plugin settings from the parent pom.
We tried to do this with <pluginManagement>, but:
"However, this only configures plugins that are actually referenced within the plugins element in the children."
http://maven.apache.org/pom.html#Plugin_Management

OK, so let's actually reference them. But that doesn't work, either. `mvn help:effective-pom` suggests that it should, and our Javadoc generation *normally* succeeds (i.e., https://google.github.io/truth/api/latest/ works) but fails when run during a release. (That said, I notice that IterableSubject.UsingCorrespondence isn't present in the "All Classes" list, so maybe Javadoc generation is half-failing?) But when I run at release time, it fails. There must be something specific to the release environment, perhaps the order in which it does things, that prevents inheritance.

So let's just declare the version everywhere. That's ugly, but it works.

Alternatively, maybe it would work if I just used <plugins> instead of <dependencyManagement><plugins>, even though that's conceptually wrong? But I haven't tried.

Here are a people with similar-sounding problems:
https://stackoverflow.com/q/40864805/28465
https://stackoverflow.com/q/31036392/28465

I didn't see any immediate red flags, but I didn't read the chat linked from the first one in detail.

Background: Without this change, I see failures like the following...

[INFO] --- maven-javadoc-plugin:2.7:jar (attach-javadocs) @ truth ---
[INFO] The goal 'org.apache.maven.plugins:maven-javadoc-plugin:2.7:javadoc' has not be previously called for the project: 'com.google.truth.extensions:truth-java8-extension:jar:0.38'. Trying to invoke it...
[ERROR] MavenInvocationException: Error when invoking Maven, consult the invoker log file: /tmp/tmp.0cuTum49a0/truth_release/core/target/invoker/maven-javadoc-plugin1331290111.txt

...where the referenced file contains errors like...

[ERROR] /tmp/tmp.0cuTum49a0/truth_release/extensions/java8/src/main/java/com/google/common/truth/StreamSubject.java:73: error: reference not found
[ERROR]    * <p>If you'd like to check that your stream contains more than {@link Integer.MAX_VALUE}

...which are the kind of thing we'd tried to suppress. (Note also the use of 2.7 rather than the requested 3.0.0.)

Next to come: a CL to fix the Javadoc errors and *intentionally* enable doclint.

-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=180846017